"""generate_capability_index.py — Generate capability discovery indexes for agent instruction files.

Generates structured Markdown sections with stable BEGIN/END markers for inclusion in
CLAUDE.md, CODEX.md, and AGENTS.md. Because those files are protected write paths,
the output is written to .governance/ supplemental files, NOT directly to the source files.

The generated sections should be reviewed by human maintainers before incorporation.

Usage:
    python tools/capability_sync/generate_capability_index.py
    python tools/capability_sync/generate_capability_index.py --agent claude
    python tools/capability_sync/generate_capability_index.py --agent codex
    python tools/capability_sync/generate_capability_index.py --agent agents
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml
    _HAS_YAML = True
except ImportError:
    _HAS_YAML = False

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_SKILLS_DIR = _REPO_ROOT / "skills"
_GOV_DIR = _REPO_ROOT / ".governance"


def load_skills() -> list[dict[str, Any]]:
    if not _HAS_YAML:
        raise RuntimeError("pyyaml required: pip install pyyaml")
    registry = _SKILLS_DIR / "registry.yaml"
    if not registry.exists():
        raise FileNotFoundError(f"skills/registry.yaml not found")
    with open(registry, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data.get("skills", [])


def load_gov_metadata() -> dict[str, Any]:
    gov_registry = _GOV_DIR / "capabilities" / "registry.yaml"
    if not _HAS_YAML or not gov_registry.exists():
        return {}
    with open(gov_registry, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return data.get("capability_metadata", {})


def build_index_table(skills: list[dict], gov_meta: dict, include_internal: bool = False) -> str:
    rows = []
    for skill in skills:
        internal = skill.get("internal", False)
        if internal and not include_internal:
            continue
        skill_id = skill.get("id", "")
        name = skill.get("name", "")
        desc = skill.get("description", "")
        category = gov_meta.get(skill_id, {}).get("category", "—")
        op_type = gov_meta.get(skill_id, {}).get("operation_type", "—")
        internal_marker = " *(internal)*" if internal else ""
        rows.append(f"| {skill_id} | `{name}`{internal_marker} | {category} | {op_type} | {desc} |")

    header = "| ID | Command | Category | Operation | Description |\n|---|---|---|---|---|\n"
    return header + "\n".join(rows)


def generate_claude_index(skills: list[dict], gov_meta: dict) -> str:
    public = [s for s in skills if not s.get("internal")]
    internal = [s for s in skills if s.get("internal")]
    total = len(skills)
    total_public = len(public)
    total_internal = len(internal)

    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    table = build_index_table(skills, gov_meta, include_internal=False)

    return f"""<!-- BEGIN GENERATED CAPABILITY INDEX -->
<!-- Generated by: tools/capability_sync/generate_capability_index.py -->
<!-- Generated at: {ts} -->
<!-- DO NOT EDIT MANUALLY — run `/sync-capabilities` to regenerate -->

## Capability Discovery (Claude Code)

**Canonical registry**: `skills/registry.yaml`
**Generated commands**: `.claude/commands/`
**Total capabilities**: {total} ({total_public} public slash commands, {total_internal} internal)

### Available Slash Commands

{table}

### Capability Governance

| Operation | Command |
|---|---|
| Check parity status | `/capability-status` |
| Run full sync | `/sync-capabilities` |
| Validate parity | `/validate-capability-parity` |
| Detect drift | `/detect-capability-drift` |
| Scaffold new capability | `/scaffold-capability` |

**Canonical contracts**: `skills/{{name}}.md`
**Generated adapters**: `.claude/commands/{{name}}.md` (frontmatter stripped, internal excluded)
**Parity report**: `.governance/generated/parity-report.yaml`
**Drift report**: `.governance/generated/drift-report.yaml`

### Capability Resolution Order

When a task requires a capability:
1. Query `skills/registry.yaml` for exact match
2. Reuse exact match if found
3. Compose existing capabilities if partial match
4. Run `/scaffold-capability` to create a genuinely missing capability
5. The new capability automatically propagates to all agent surfaces

<!-- END GENERATED CAPABILITY INDEX -->"""


def generate_codex_index(skills: list[dict], gov_meta: dict) -> str:
    total = len(skills)
    total_public = sum(1 for s in skills if not s.get("internal"))
    total_internal = sum(1 for s in skills if s.get("internal"))

    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    table = build_index_table(skills, gov_meta, include_internal=True)

    return f"""<!-- BEGIN GENERATED CAPABILITY INDEX -->
<!-- Generated by: tools/capability_sync/generate_capability_index.py -->
<!-- Generated at: {ts} -->
<!-- DO NOT EDIT MANUALLY — run sync-capabilities to regenerate -->

## Capability Discovery (Codex / Generic Agents)

**Canonical registry**: `skills/registry.yaml`
**Skill root**: `.agents/skills/{{name}}/SKILL.md`
**Total capabilities**: {total} ({total_public} public, {total_internal} internal)

### Available Skills

{table}

### Capability Governance

| Operation | Command |
|---|---|
| Check parity status | Run `python tools/capability_sync/validate_semantic_parity.py --check` |
| Run full sync | Run `python tools/capability_sync/run_sync.py` |
| Detect drift | Run `python tools/capability_sync/detect_adapter_drift.py --check` |

**Canonical contracts**: `skills/{{name}}.md`
**Agent adapters**: `.agents/skills/{{name}}/SKILL.md` (frontmatter preserved, all skills)
**Parity report**: `.governance/generated/parity-report.yaml`

### Capability Resolution Order

When a task requires a capability:
1. Query `.agents/skills/` for exact match
2. Reuse the `SKILL.md` from that directory
3. Reference canonical `skills/{{name}}.md` for full contract
4. If no match: request `/scaffold-capability` through Claude Code
5. The new capability propagates to `.agents/skills/` automatically

<!-- END GENERATED CAPABILITY INDEX -->"""


def generate_agents_index(skills: list[dict], gov_meta: dict) -> str:
    total = len(skills)
    total_public = sum(1 for s in skills if not s.get("internal"))
    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    return f"""<!-- BEGIN GENERATED CAPABILITY INDEX -->
<!-- Generated by: tools/capability_sync/generate_capability_index.py -->
<!-- Generated at: {ts} -->
<!-- HUMAN REVIEW REQUIRED — This section is generated for AGENTS.md inclusion -->
<!-- AGENTS.md is a protected file. Human maintainers must review and incorporate this. -->

## §12: Capability Registry (Generated Index)

> This section is generated from `skills/registry.yaml`. Do not edit manually.
> Run `python tools/capability_sync/run_sync.py` to regenerate.

**Canonical registry**: `skills/registry.yaml`
**Total capabilities**: {total} ({total_public} public, {total - total_public} internal)
**Governance tooling**: `tools/capability_sync/`

### Capability Resolution Mandate

All supported agents must use the same capability resolution order:
1. DECOMPOSE TASK INTO CAPABILITIES
2. QUERY `skills/registry.yaml` for exact match
3. REUSE EXACT MATCH → `.claude/commands/` (Claude Code) or `.agents/skills/` (Codex)
4. COMPOSE EXISTING CAPABILITIES if partial match found
5. REPAIR BROKEN CAPABILITY if adapter exists but fails
6. EXTEND EXISTING CAPABILITY rather than create a new one
7. CREATE SMALLEST MISSING MICRO-CAPABILITY → run `/scaffold-capability`
8. REGISTER → SYNCHRONIZE ADAPTERS → TEST → USE FOR ORIGINAL TASK

### Parity Enforcement

- Local: `python tools/capability_sync/run_sync.py`
- Pre-commit: `scripts/pre-commit-audit.sh` (steps 1-6)
- CI: `.github/workflows/skill-governance.yml` (job: capability-parity)

<!-- END GENERATED CAPABILITY INDEX -->"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate capability discovery indexes for agent instruction files.")
    parser.add_argument("--agent", choices=["claude", "codex", "agents", "all"], default="all")
    args = parser.parse_args(argv)

    try:
        skills = load_skills()
        gov_meta = load_gov_metadata()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    targets = {
        "claude": (_GOV_DIR / "CLAUDE_CAPABILITY_INDEX.md", generate_claude_index),
        "codex": (_GOV_DIR / "CODEX_CAPABILITY_INDEX.md", generate_codex_index),
        "agents": (_GOV_DIR / "AGENTS_CAPABILITY_INDEX.md", generate_agents_index),
    }

    agents_to_generate = list(targets.keys()) if args.agent == "all" else [args.agent]

    for agent in agents_to_generate:
        out_path, generator_fn = targets[agent]
        content = generator_fn(skills, gov_meta) + "\n"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        print(f"Generated {out_path.relative_to(_REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
